// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMVCMappingDEMO.Data;

#nullable disable

namespace MyMVCMappingDEMO.Migrations
{
    [DbContext(typeof(MechEmpDbContext))]
    [Migration("20250813141719_Edit RollNumber")]
    partial class EditRollNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyMVCMappingDEMO.Models.MechEmployee", b =>
                {
                    b.Property<int>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MId"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MRollNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MYearPassed")
                        .HasColumnType("int");

                    b.HasKey("MId");

                    b.ToTable("MechEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
